### ISSUE TITLE
How download from scribd

### ISSUE THREAD

**Issue by mohseneslami** [christiancoleman/scribd_book_downloader#1]
I have ID and token

362762806

1556832274_3I2UY6PLBTH7YFYQQHA6KWQRJGCEHQV5GNHF45PLEFT23ELF4ZVU73YXTJYQ4===_c1c8e067e39aeacc874b533e51ce183f334164f2

How download by main.py ?

**Comment by christiancoleman** [comment]
Hey sorry only got this now.

I haven't tested this lately, but at the time of creation all you needed to was run:

**python main.py**

then you would copy and paste your ID and token as the program asks for it.

**Comment by christiancoleman** [comment]
@mohseneslami I just ran some tests and this version definitely doesn't work any longer. They changed their backend dramatically. Will require an entire rewrite.
